apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Apps\Scoop\apps\kompose\current\kompose.exe convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: elastic
  name: elastic
spec:
  ports:
  - name: "9200"
    port: 9200
    targetPort: 9200
  - name: "9300"
    port: 9300
    targetPort: 9300
  selector:
    io.kompose.service: elastic
status:
  loadBalancer: {}
