apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Apps\Scoop\apps\kompose\current\kompose.exe convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: server
    spec:
      containers:
      - args:
        - npm
        - start
        env:
        - name: ELASTICSEARCH_URL
          value: http://localhost:9200
        image: epikem/vocabo-server
        name: server
        ports:
        - containerPort: 3001
        resources: {}
      restartPolicy: Always
status: {}
