apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Apps\Scoop\apps\kompose\current\kompose.exe convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: client
  name: client
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: client
      namespace: vocabo-cluster
      name: client
    spec:
      hostname: vocabo
      subdomain: client
      containers:
      - args:
        - npm
        - start
        env:
        - name: NODE_ENV
          value: production
        - name: SERVER_URL
          value: server.vocabo-cluster.svc.cluster.local:3001
        image: epikem/vocabo-client
        name: client
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
