apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Apps\Scoop\apps\kompose\current\kompose.exe convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3001
  - name: "3001"
    port: 3001
    targetPort: 3001
  selector:
    app: app
    io.kompose.service: app
status:
  loadBalancer: {}
