apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Apps\Scoop\apps\kompose\current\kompose.exe convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: elastic
  name: elastic
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: elastic
      namespace: vocabo-cluster
      name: elastic
    spec:

      hostname: vocabo
      subdomain: elastic
      containers:
      - env:
        - name: discovery.type
          value: single-node
        image: epikem/elastic-built:0.1
        name: elastic
        ports:
        - containerPort: 9200
        - containerPort: 9300
        resources: {}
        volumeMounts:
        - mountPath: ./docker/elastic
          name: elastic-claim0
      restartPolicy: Always
      volumes:
      - name: elastic-claim0
        persistentVolumeClaim:
          claimName: elastic-claim0
status: {}
